testing breaks
when inputs for destroy: True or epsilon grain: 0 - the code throws
errors with  mdust_gg = md * f_c * (1.-((md/g)/z)) * time_gg**-1
ZeroDivisionError: 0.0 cannot be raised to a negative power

e.g.